name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # use the version you're targeting

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
